### ISSUE TITLE
Consider redesigning API to be more consise

### ISSUE THREAD

**Issue by lpil** [mooreryan/gleam_qcheck#1]
Hello!

Thank you for this library. I'm looking forward to giving the standard library a good test with it.

One thing I think could be improved a little with this library is the API. Currently it looks like this:

```gleam
pub fn small_positive_or_zero_int__test() {
  qtest.run(
    config: qtest_config.default(),
    generator: generator.small_positive_or_zero_int(),
    property: fn(n) { n + 1 == 1 + n },
  )
  |> should.equal(Ok(Nil))
}
```

It is quite verbose, with `config: qtest_config.default()` and `|> should.equal(Ok(Nil))` being boilerplate.

Perhaps it could be rewritten to be more like this:

```gleam
pub fn small_positive_or_zero_int__test() {
  use n <- qtest.given(qtest.small_positive_or_zero_int())
  { n + 1 }
  |> should.equal(1 + n)
}
```

And when `assert` lands in Gleam it could then be upgraded to this:

```gleam
pub fn small_positive_or_zero_int__test() {
  use n <- qtest.given(qtest.small_positive_or_zero_int())
  assert n + 1 == 1 + n
}
```

There could be additional `given`-like functions for supplying config, for generating multiple values, and so on.

I like this approach as:
- There is less code to write and read, and there is no boilerplate that might otherwise obscuring the logic of the test when reading quickly.
- The use of panics rather than returning a bool makes it easier to have a test fail
  - There's no need for the additional complexity of getting the bool back up to the top level
  - There's no chance of "boolean blindness" in getting the value inverted
  - There's no chance of bool-handling logic obscuring the intent of the test)
  - It is more familiar to your average programmer.
- There is only one module to import (it is unlikely that there is an existing `small_positive_or_zero_int` function in the `qtest` module which would clash.
- It's "prettier"! Us programmers can be superficial folks and care about the aesthetics of code 😁 

Thanks for reading!

**Comment by mooreryan** [comment]
Thanks for your interesting suggestions--the code you show does have a nice, compact feel to it! Let me implement these ideas and see how they feel.

Here are some fairly unorganized general thoughts.

- qtest functions that don't require passing in the default config is a good idea I think
  - Originally I had thought of creating a `TestSpec` and passing that in to the `run` function rather than the way it currently is, which is how OCaml's qcheck does it, 
  - but having the functions with defaults baked in a nice alternative to that (and to what it currently is as well)
- I'm not sure I understand what you mean by having properties with panics being simpler to use than properties that return bool.
  - It feels shorter and simpler to not have to panic--I mean to say, running predicate functions over data seems quite straightforward, and seems to me the essence of a property (and you don't have to write the extra assert). So I'm not sure about the more familiar part.
    - Also, there are many times (in ocaml at least) where I write properties that basically say `x == y` or `x != y` and not having to write asserts feels nice. (Though that is subjective of course.)
  - You would need the FFI to catch the panics so that shrinking can occur. 
    - Not a big deal, I can steal your erlang [rescue](https://github.com/gleam-lang/erlang/blob/9e7e6cdac92f284f65980f49bd57759da07ace2d/src/gleam_erlang_ffi.erl#L37) function :smile_cat: 
  - But, it is a really good point about not having to check the `qtest.run` return value at the top-level though...
    - any property that panics fails and any property that doesn't passes, which means user will not have to check return value of `qtest.run` (which is annoying). 
    - I think you're right that that aspect is nicer.
  - And another point in favor of panicking properties--there wouldn't need to be separate runners for different kinds of properties.
    - Now there is one for checking a result is `Ok`, but you could imagine more that say should be false, or should be `Some` or ...you get the picture.
    - With the panicking property, those could all be avoided, which is nice I think.
- On the surface, I'm not sure about the idea of mixing in generators and generator their utility functions to the `qtest` module (this is of course very subjective).
  - It feels like mixing in sort of separate concerns into one mega-module.
    - In OCaml, I generally mint a new module for (pretty much) every type, so that is probably biasing me in a certain way regarding the big modules.  
    - However, this isn't OCaml, and I'm pretty sure I have seen you mention preferring fewer/larger modules on the forum....so I will have to give it more thought.
  - Though I do understand your point about having less modules to import being a nice change.
  - Generators have bind, map, apply, and trees have bind, map, apply
    - Ideally users wouldn't have to use the tree ones mostly so sticking the generator combinators into the qtest module might be okay, 
    - but then you would have `qtest.map` and does that apply to some `qtest` structure or to the generator?
      - Or you could put them in like `qtest.generator_map`, `qtest.generator_apply`, but that doesn't feel so nice if the other generator functions aren't prefixed.

Anyway, thanks for the feedback--there's some interesting stuff to think about!

**Comment by lpil** [comment]
> I'm not sure I understand what you mean by having properties with panics being simpler to use than properties that return bool. 

Say you have some nested data structure, and you wish to check that all of some inner values have some property. If the API is bool based you need to write some code that bubbles up any `False` back to the top. This will be more error prone than crashing, which you can do anywhere.

The same is true for tests that check more than one thing and short circuit. The code changes from being a linear sequence of assertions to a more complex nested conditional structure.

> You would need the FFI to catch the panics so that shrinking can occur. 

I tend to use this package here: https://github.com/lpil/exception

> It feels like mixing in sort of separate concerns into one mega-module. 

From the user's point of view I think they're all the concern of writing property tests, and for me the external API trumps all. Convenience and minimal cognitive overhead and removing the risk of needing to alias `qtest` modules to avoid clashing with application modules are attractive to me. That said I don't know the full scope of the API so I've less context here.

> but then you would have qtest.map and does that apply to some qtest structure or to the generator? 

Are there multiple public data types which it would have `map` implemented for?

**Comment by mooreryan** [comment]
As of [v0.0.3](https://github.com/mooreryan/gleam_qcheck/blob/main/CHANGELOG.md#003---2024-05-15):
  - Panics in properties are now treated as failures and trigger shrinking.
  - `qtest` has some `given` style helper functions to make things more convenient when using the default config
  - The API is still broken up into different modules, but this can be revisited in the future if necessary.

I will close this for now, as at least some of your requests were addressed :smile_cat:.  Feel free to re-open if more discussion is warranted, or if there are any other API suggestions!

**Comment by mooreryan** [comment]
You're were right @lpil the single module interface is very pleasant to work with. It is that way as of [v0.0.4](https://github.com/mooreryan/gleam_qcheck/releases/tag/v0.0.4)
